language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libudev-dev libusb-1.0-0-dev autotools-dev autoconf automake libtool
  - git clone git@github.com:signal11/hidapi.git
  - cd hidapi
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd -

script: make
