os:
  - linux

addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - cmake
      - libudev-dev
      - libusb-1.0-0-dev
      - autotools-dev
      - autoconf
      - automake
      - libtool

before_install:
  - wget https://github.com/signal11/hidapi/archive/master.zip -O /tmp/hidapi.zip
  - unzip /tmp/hidapi.zip -d /tmp
  - cd /tmp/hidapi-master
  - ./bootstrap
  - ./configure
  - make
  - cd -

language: c

script:
  - mkdir _build
  - cd _build
  - cmake .. -DCMAKE_C_FLAGS="-I/tmp/hidapi-master -L/tmp/hidapi-master/libusb/.libs/"
  - export
  - make
